name: jaspr_test
description: Testing utilities for jaspr.
version: 0.13.3
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

topics:
  - jaspr
  - web
  - testing

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  html: ^0.15.0
  http: '>=0.13.0 <2.0.0'
  jaspr: ^0.13.3
  meta: ^1.7.0
  test: ^1.22.0

dev_dependencies:
  lints: ^3.0.0
